this `object` in the anonymous class breaks at runtime
Mar 18 07:04:16 anand lila[20263]: at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Mar 18 07:04:16 anand lila[20263]: [ERROR] [03/18/2016 07:04:16.139] [lila-akka.actor.default-dispatcher-10] [akka.actor.ActorSystemImpl(lila)] Uncaught fatal error from thre
ad [lila-akka.actor.default-dispatcher-10] shutting down ActorSystem [lila]
Mar 18 07:04:16 anand lila[20263]: java.lang.NoClassDefFoundError: lila/mon$fishnet$analysis/by$$anon$total$
Mar 18 07:04:16 anand lila[20263]: at lila.fishnet.Monitor.analysis(Monitor.scala:34)
Mar 18 07:04:16 anand lila[20263]: at lila.fishnet.FishnetApi.lila$fishnet$FishnetApi$$$anonfun$30(FishnetApi.scala:88)
Mar 18 07:04:16 anand lila[20263]: at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
Mar 18 07:04:16 anand lila[20263]: at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
Mar 18 07:04:16 anand lila[20263]: at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)