swap vals to work around likely miscompilation
Revert this and load /swiss to get:

    java.lang.NullPointerException: Cannot invoke "scala.Function1.apply(Object)" because "this.loader" is null
    [info] 	at com.github.blemale.scaffeine.AsyncCacheLoaderAdapter.asyncLoad(AsyncCacheLoaderAdapter.java:28)
    [info] 	at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.lambda$newMappingFunction$0(LocalAsyncLoadingCache.java:68)
    [info] 	at com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$get$2(LocalAsyncCache.java:94)
    [info] 	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$2(LocalCache.java:167)
    [info] 	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2685)
    [info] 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
    [info] 	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2683)
    [info] 	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2666)
    [info] 	at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:92)
    [info] 	at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:83)